# ============================== docker-compose.yml ===========================
# version: "3.9"
# services:
#   web:
#     build: .
#     command: flask run --host=0.0.0.0 --port=5000
#     env_file: .env
#     environment:
#       - OLLAMA_API_URL=http://host.docker.internal:11434/api/generate
#     volumes:
#       - .:/app
#     ports:
#       - "5000:5000"
#     depends_on:
#       - redis
#   worker:
#     build: .
#     command: celery -A worker.celery worker --loglevel=INFO
#     env_file: .env
#     environment:
#       - OLLAMA_API_URL=http://host.docker.internal:11434/api/generate
#     volumes:
#       - .:/app
#     depends_on:
#       - redis
#   redis:
#     image: redis:7-alpine
#     ports:
#       - "6379:6379