services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro